### ISSUE TITLE
Square Cannot Create Card

### ISSUE THREAD

**Issue by nathanaelphilip** [woocommerce/woocommerce-square#369]
When trying to store a card, the Square API sends back this response:

```
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => INVALID_CARD_DATA
            [detail:Square\Models\Error:private] => Invalid card data.
            [field:Square\Models\Error:private] => source_id
        )

)
```

<details><summary>System Status Report</summary>

```
### WordPress Environment ###

WordPress address (URL): [Redacted]
Site address (URL): [Redacted]
WC Version: 9.9.4
Legacy REST API Package Version: ✔ 1.0.5
Action Scheduler Version: ✔ 3.9.2
Log Directory Writable: ✔
WP Version: 6.8.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
Server Architecture: Linux 4.19.286-203.ELK.el7.x86_64 x86_64
PHP Version: 8.2.18
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 8.7.1
OpenSSL/1.1.1w

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

[REDACTED]

### Post Type Counts ###

attachment: 1795
avada_portfolio: 1
custom_css: 3
frm_form_actions: 6
frm_styles: 1
fusion_element: 29
fusion_form: 3
fusion_tb_layout: 7
fusion_tb_section: 16
fusion_template: 3
jb_store_css: 13
jetpack_migration: 2
mc4wp-form: 1
ml-slide: 20
ml-slider: 2
nav_menu_item: 31
oembed_cache: 3
page: 74
post: 192
product: 242
product_variation: 435
revision: 1202
shop_coupon: 43
shop_order: 18298
shop_order_refund: 251
shop_subscription: 395
slide: 91
tt_font_control: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.4
Code Snippets: by Code Snippets Pro – 3.6.8
GTM4WP - A Google Tag Manager (GTM) plugin for WordPress: by Thomas Geiger – 1.21.1
Easy Google Fonts: by Titanium Themes – 2.0.4
Formidable Forms: by Strategy11 Form Builder Team – 6.22
Avada Builder: by ThemeFusion – 3.12.1
Avada Core: by ThemeFusion – 5.12.1
GA Google Analytics: by Jeff Starr – 20250326
Hide Shipping Method For WooCommerce: by theDotstore – 1.5.2
Smash Balloon Instagram Feed: by Smash Balloon – 6.9.1
Jetpack Boost: by Automattic - Jetpack Site Speed team – 4.1.0
Jetpack: by Automattic – 14.7
KIA Subtitle: by Kathy Darling – 4.0.1
Official StatCounter Plugin: by Aodhan Cullen – 2.1.0
PixelYourSite: by PixelYourSite – 11.0.0.3
Redirection: by John Godley – 5.5.2
Relevanssi: by Mikko Saari – 4.24.6
UpdraftPlus - Backup/Restore: by TeamUpdraft
DavidAnderson – 1.25.6

Checkout Field Editor for WooCommerce: by ThemeHigh – 2.1.4
WooCommerce.com Update Manager: by Automattic – 1.0.3
WooCommerce All Products for Subscriptions: by Woo – 6.0.6
Pixel Manager for WooCommerce: by SweetCode – 1.49.1
WooCommerce Legacy REST API: by WooCommerce – 1.0.5
WooCommerce Product Bundles: by Woo – 8.4.1
WooCommerce Tax: by WooCommerce – 3.0.3
WooCommerce Shipping: by WooCommerce – 1.7.3
WooCommerce Square: by WooCommerce – 4.9.4
WooCommerce Subscriptions: by WooCommerce – 7.6.0
WooCommerce: by Automattic – 9.9.4
WP Mail Logging: by WP Mail Logging Team – 1.14.0
WP Migrate: by WP Engine – 2.7.4
WP Activity Log: by Melapress – 5.4.1
Smush: by WPMU DEV – 3.18.1

### Inactive Plugins (1) ###

WooCommerce Blocks: by Automattic – 11.7.0

### Must Use Plugins (4) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 2.2.2
SSO: by Garth Mortensen
Mike Hansen – 0.4

WP Migrate Compatibility: by Delicious Brains – 1.3

### Settings ###

Legacy API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –
Enabled Features: analytics
marketplace
order_attribution
site_visibility_badge
remote_logging
blueprint


### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 2 MB

### WC Pages ###

Shop base: #20735 - /shop/
Cart: #3587 - /cart/ -  Contains the woocommerce_cart shortcode
Checkout: #3588 - /checkout/ -  Contains the woocommerce_checkout shortcode
My account: #3589 - /my-account/ -  Contains the [woocommerce_my_account] shortcode
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 7.12.1
Parent Theme Author URL: https://themeforest.net/user/ThemeFusion
Theme type: Classic theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada-Child-Theme/woocommerce/emails/admin-new-order.php version 3.7.0 is out of date. The core version is 9.8.0
Avada-Child-Theme/woocommerce/emails/customer-processing-order.php version 3.7.0 is out of date. The core version is 9.9.0
Avada-Child-Theme/woocommerce/emails/customer-reset-password.php version 4.0.0 is out of date. The core version is 9.8.0
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌
					
					
						Learn how to update					 |
					
						
					
					
						Clear system status theme info cache

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://mrespresso.com
Subscriptions-core Library Version: 8.3.0
Subscription Statuses: wc-active: 76
wc-expired: 111
wc-pending-cancel: 3
wc-pending: 7
wc-on-hold: 21
wc-cancelled: 177

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Subscriptions by Payment Gateway ###

Square: wc-active: 76
wc-cancelled: 177
wc-expired: 111
wc-on-hold: 21
wc-pending: 7
wc-pending-cancel: 3


### Payment Gateway Support ###

Square: products
card_types
payment_form
authorization
charge
charge-virtual
capture_charge
refunds
voids
customer_id
tokenization
add_payment_method
token_editor
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin


### Product Bundles ###

Database Version: 8.4.1
Loopback Test: ✔
Template Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
onboarding
onboarding-tasks
pattern-toolkit-full-composability
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
printful
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page
launch-your-store
add-to-cart-with-options-stepper-layout
disable-core-profiler-fallback

Disabled Features: product-data-views
experimental-blocks
coming-soon-newsletter-template
minified-js
point-of-sale
product-pre-publish-modal
settings
async-product-editor-category-field
product-editor-template-system
use-wp-horizon
blockified-add-to-cart

Daily Cron: ✔ Next scheduled: 2025-06-19 16:51:18 -07:00
Options: ✔
Notes: 202
Onboarding: completed

### All Products for WooCommerce Subscriptions ###

Template Overrides: –

### Action Scheduler ###

Complete: 3,255
Oldest: 2025-05-18 13:07:01 -0700
Newest: 2025-06-18 12:58:09 -0700

Failed: 2,281
Oldest: 2022-03-10 09:56:38 -0800
Newest: 2025-06-18 12:54:07 -0700

Pending: 107
Oldest: 2025-06-18 13:02:47 -0700
Newest: 2026-10-31 09:05:59 -0700


### Status report information ###

Generated at: 2025-06-18 13:01:12 -07:00
```
</details>

**Comment by jeffpaul** [comment]
@nathanaelphilip there a couple different ways a card could be stored and with any number of product configurations.  Can you share the more precise scenario you are running into here so we can more quickly try to replicate and better help triage?  (cc: @imodouglas)

**Comment by nathanaelphilip** [comment]
When a user goes to checkout and selects “store card for future purchases” or when they try to create a subscription product, this error is triggered.

**Comment by nathanaelphilip** [comment]
The 4.9.5 update seems to have fixed the issue on new customers, but if you’re a returning customer, it fails again when trying to created a card (same issue as above).

Is there a way to escalate this issue?

**Comment by jeffpaul** [comment]
@nathanaelphilip can you confirm whether the reproduction steps are the same for returning customers?  Having details on the request body in cases where this error occurs will help us further triage here.

**Comment by dgogia-creator** [comment]
It's been a major issue in our production environment as well and we're losing revenue big time. I've tried both versions 4.9.5 and 4.9.6 with WooCommerce 10.0.2
Here are the two scenarios:
1: Existing customer with expired  ccof trying to update a new card gets "Invalid card Data" error with the same "square-credit-card" log file as shown above. 
2: New customer  trying to place order. Customer ID is created in square but not updated on wp/wc_user. Same error message "Invalid Card Data".

From what I believe is the issue could be the source ID and verification token are the same and when using a Create_Card transaction the verification token should be ignored.  source_id":"cnon:CA4SEOgnnrWU3tTgW-sSHctjmRQYASgB","verification_token":"cnon:CA4SEOgnnrWU3tTgW-sSHctjmRQYASgB". I'm not a developer but looking at the logs, it could be the issue. 

Need this Fix asap as we're paying for Clicks to Google and Microsoft ads to get new customers but they can't pay and we lose money on the acquisition cost as well as revenue. Its going on for over a month now with no fix.

**Comment by iamdharmesh** [comment]
Thanks for reporting this @nathanaelphilip, and for providing additional details @dgogia-creator. Apologies for the inconvenience this issue has caused you.

If possible, could you please share the request body logs related to this issue? (Kindly make sure to redact any confidential information.) This will help us identify the root cause and work toward a resolution. 

Thank you!

**Comment by bigscaryduck** [comment]
I am also experiencing this issues on my sites and it is causing major customer service issues. 

Am I correct in thinking this pull request will fix this issue? https://github.com/woocommerce/woocommerce-square/pull/379

**Comment by Sidsector9** [comment]
Related discussions in Square forum:

- https://developer.squareup.com/forums/t/invalid-card-data-when-create-authorized-payment/10767
- (Bad Address) https://developer.squareup.com/forums/t/invalid-card-data-field-source-id-in-production/11860 
- (Incorrect Zip code) https://developer.squareup.com/forums/t/invalid-card-data-field-source-id-in-sandbox/9332/6 
- (Zip code) https://developer.squareup.com/forums/t/credit-card-with-incorrect-postal-code-succeeds/7204/4
- (Incorrect Card number, CVV or Exp date) https://developer.squareup.com/forums/t/large-number-of-declines-invalid-card-number/14806/3
- (Incorrect Zip code) https://developer.squareup.com/forums/t/create-card-error-invalid-request-error/8096
- (Incorrect Zip code on file) https://developer.squareup.com/forums/t/passing-payment-id-to-cards-source-id-causing-invalid-card-data/8876/5

**Comment by Sidsector9** [comment]
@nathanaelphilip @dgogia-creator @bigscaryduck I have some follow-up questions:

1. Does the issue happen for a single, few or large number of customers?
2. Was the Square account switched between Sandboxed and Production modes recently in the plugin?
3. Was the Customer ID updated in the plugin recently?
4. Do you have any details on what kind of products are present in the cart when this issue arises? I'm trying to determine whether the issue arises whenever a subscription product is present in the cart.

@dgogia-creator some specific questions for you:

> Existing customer with expired ccof trying to update a new card gets "Invalid card Data" error with the same "square-credit-card" log file as shown above.

As far as I know, `ccof` does not expire on its own unless it was deleted from the customer profile, or if the card issuer does not use a Card Updater Service. Can you explain in what scenario the `ccof` would expire?

Additionally, if the customer is trying to update an expired card, can they first try to delete their card from My Account > Payment Method, and re-enter the renewed/new card?

> New customer trying to place order. Customer ID is created in square but not updated on wp/wc_user. Same error message "Invalid Card Data".

If you visit the Customer's profile admin page, you'll see a text field called **Customer ID**. Can you please verify if the Customer ID exists for the new customer?

This will help us narrow down the issue. Thanks in advance!

**Comment by dgogia-creator** [comment]
Replies inline>Does the issue happen for a single, few or large number of customers? Answer: Happens with all customers.
Was the Square account switched between Sandboxed and Production modes recently in the plugin?Answer-just upgraded version.
Was the Customer ID updated in the plugin recently? Answer-No , no changes
Do you have any details on what kind of products are present in the cart when this issue arises? I'm trying to determine whether the issue arises whenever a subscription product is present in the cart.-  Answer-Any product. Even if the customer tries to add card from his account dashboard using add payment update payment method option.Sent via the Samsung Galaxy S24 Ultra, an AT&T 5G smartphone
-------- Original message --------From: Siddharth Thevaril ***@***.***> Date: 7/22/25  10:43 AM  (GMT-05:00) To: woocommerce/woocommerce-square ***@***.***> Cc: dgogia-creator ***@***.***>, Mention ***@***.***> Subject: Re: [woocommerce/woocommerce-square] Square Cannot Create Card (Issue #369) Sidsector9 left a comment (woocommerce/woocommerce-square#369)
@nathanaelphilip @dgogia-creator @bigscaryduck I have some follow-up questions:

Does the issue happen for a single, few or large number of customers?
Was the Square account switched between Sandboxed and Production modes recently in the plugin?
Was the Customer ID updated in the plugin recently?
Do you have any details on what kind of products are present in the cart when this issue arises? I'm trying to determine whether the issue arises whenever a subscription product is present in the cart.

@dgogia-creator some specific questions for you:

Existing customer with expired ccof trying to update a new card gets "Invalid card Data" error with the same "square-credit-card" log file as shown above.

As far as I know, ccof does not expire on its own unless it was deleted from the customer profile. Can you explain in what scenario the ccof would expire?

New customer trying to place order. Customer ID is created in square but not updated on wp/wc_user. Same error message "Invalid Card Data".

If you visit the Customer's profile admin page, you'll see a text field called Customer ID. Can you please verify if the Customer ID exists for the new customer?
This will help us narrow down the issue. Thanks in advance!

**Comment by bigscaryduck** [comment]
**Does the issue happen for a single, few or large number of customers?**
Started happening to a large number of customer about a week ago, I would say 3 in 5 customers based on our logs. 

**Was the Square account switched between Sandboxed and Production modes recently in the plugin?**
No, we never switched to Sandboxed. I did reset the connection to Square initially thinking that might be an issue. 

**Was the Customer ID updated in the plugin recently?**
No, no changes. 

**Do you have any details on what kind of products are present in the cart when this issue arises? I'm trying to determine whether the issue arises whenever a subscription product is present in the cart.**
I have confirmed it happens with new subscriptions, single purchase and it occurs during Guest Checkout as well as Create an Account checkout. 

A few more notes:
- We have had some customers show success by trying a different card
- We have seen it fail 5+ times for the same card
- It does seem to happen more often to past customers but it is also happening to new customers. It is hard to tell as we have logs but Square doesn't have any record of the failed attempts when I reach out to their support. 
- It is not happening for any specific card type, we have seen it fail for Visa, MasterCard and Amex. 
- Existing subscriptions recur without issue so far.

**Comment by Sidsector9** [comment]
> Even if the customer tries to add card from his account dashboard using add payment update payment method option.

@qasumitbagthariya I think we should try reproducing this using a production account. Use the Ramp card or personal credit cards to add/update the payment methods.

**Comment by dgogia-creator** [comment]
Yes. That's correct. Here's the 400 error and I believe it's because we're getting duplicate SourceID and Verification token: Develops please resolve this asap.

body: {"idempotency_key":"db4c7b19c6a15f12b3943c9751b0f523a3fdf265","source_id":"cnon:CA4SEE78oKLNF7gjqxUduXo2tIIYASgB","verification_token":"cnon:CA4SEE78oKLNF7gjqxUduXo2tIIYASgB","card":{"cardholder_name":"dummy","billing_address":{"address_line_1":"dummy road","address_line_2":"","locality":"nyc","administrative_district_level_1":"GA","postal_code":"30701","country":"US","first_name":"dummy","last_name":"doe"},"customer_id":"C4SND9J5JCV0ZET0BW72YCS16R"}}
duration: 0.3945s
 CONTEXT: {"_legacy":true}
2025-07-23T12:31:34+00:00 Notice Response
code: 400

**Comment by bigscaryduck** [comment]
If it helps this is what my "square_credit_card" logs show. This is a new customer attempting with multiple different cards:

```
2025-07-23T02:10:02+00:00 NOTICE Square.js Response:
 Array
(
    [brand] => VISA
    [expMonth] => XX
    [expYear] => XXXX
    [last4] => 0002
)
 CONTEXT: {"_legacy":true}
2025-07-23T02:10:02+00:00 NOTICE [Performance] generate_payment_nonce completed in 1.101s with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:10:02+00:00 NOTICE [Performance] validate_payment_data completed in 0ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:10:03+00:00 NOTICE [Performance] validate_payment_data completed in 3ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:10:03+00:00 NOTICE Request
method:
uri: createCustomer
user-agent: WooCommerce-Square/4.9.4 (WooCommerce/10.0.2; WordPress/6.8.2)
headers: Array
(
)
body:
duration: 0.296s
 CONTEXT: {"_legacy":true}
2025-07-23T02:10:03+00:00 NOTICE Response
code: 200
message:
headers: Array
(
    [0] => HTTP/2 200
    [date] => Wed, 23 Jul 2025 02:10:03 GMT
    [content-type] => application/json
    [content-length] => 340
    [cf-ray] => 9637a3a49fdaf828-IAD
    [cf-cache-status] => DYNAMIC
    [content-encoding] => gzip
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [vary] => Accept-Encoding
    [frame-options] => DENY
    [square-version] => 2025-01-23
    [squareup--connect--v2--common--versionmetadata-bin] => CgoyMDI1LTAxLTIz
    [x-content-type-options] => nosniff
    [x-envoy-decorator-operation] => /v2/customers/**
    [x-frame-options] => DENY
    [x-sq-dc] => aws
    [x-sq-istio-migration-ingress-proxy] => sq-envoy
    [x-sq-istio-migration-ingress-region] => us-west-2
    [x-sq-region] => us-west-2
    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm=94Xpp4gjDLKTnLS5ClFAcfGMrWLlUaceCh909SLezRs-1753236603-1.0.1.1-2HswEnHiKwiyYVhpTNpuzeHzRLMdrdBNq_I_A7V3KBHXPtranaWQSnl02.Ap2CVP7AuAVDkMLfVPgh3UgDxXxF2phFVd5a1Ud67DwfPg1Ss; path=/; expires=Wed, 23-Jul-25 02:40:03 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [server] => cloudflare
)
body: {
    "customer": {
        "id": "D0C9P1SV5ZPMEP5064CCNB20Q8",
        "created_at": "2025-07-23T02:10:03.756Z",
        "updated_at": "2025-07-23T02:10:03Z",
        "given_name": "Dummy",
        "family_name": "Dummy",
        "email_address": "Dummy@gmail.com",
        "address": {
            "address_line_1": "Dummy",
            "locality": "Dummy",
            "administrative_district_level_1": "CA",
            "postal_code": "95222",
            "country": "US"
        },
        "phone_number": "XXXXXXXXXX",
        "preferences": {
            "email_unsubscribed": false
        },
        "creation_source": "THIRD_PARTY",
        "version": 0
    }
}
 CONTEXT: {"_legacy":true}
2025-07-23T02:10:04+00:00 NOTICE Request
method:
uri: createCard
user-agent: WooCommerce-Square/4.9.4 (WooCommerce/10.0.2; WordPress/6.8.2)
headers: Array
(
)
body:
duration: 0.39137s
 CONTEXT: {"_legacy":true}
2025-07-23T02:10:04+00:00 NOTICE Response
code: 400
message:
headers: Array
(
    [0] => HTTP/2 400
    [date] => Wed, 23 Jul 2025 02:10:04 GMT
    [content-type] => application/json
    [content-length] => 134
    [cf-ray] => 9637a3a65ba9f828-IAD
    [cf-cache-status] => DYNAMIC
    [content-encoding] => gzip
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [vary] => Origin, Accept-Encoding
    [square-version] => 2025-01-23
    [x-content-type-options] => nosniff
    [x-download-options] => noopen
    [x-envoy-decorator-operation] => /v2/cards/**
    [x-frame-options] => SAMEORIGIN
    [x-permitted-cross-domain-policies] => none
    [x-speleo-traceid] => CDN-6e4352c4-2523-4883-bf84-8446012fa7f4
    [x-sq-dc] => aws
    [x-sq-istio-migration-ingress-proxy] => sq-envoy
    [x-sq-istio-migration-ingress-region] => us-east-1
    [x-sq-region] => us-east-1
    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm=2APGm.aMGmN_tr_tRfs7Wb7vYtaGXfVHB8sYx9Bj5d0-1753236604-1.0.1.1-Knq8wkO6ZVRoveN3SnGTyQn7WzCvidoxy4lq_ywTXp9xFlQqP3TsItfgPqEOOULcpJAUp1UiYn7tRsJXhHJA68nPM2at6xX.0UUDnaBfeVI; path=/; expires=Wed, 23-Jul-25 02:40:04 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [server] => cloudflare
)
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => INVALID_CARD_DATA
            [detail:Square\Models\Error:private] => Invalid card data.
            [field:Square\Models\Error:private] => source_id
        )

)
 CONTEXT: {"_legacy":true}
2025-07-23T02:11:01+00:00 NOTICE [Performance] validate_payment_data completed in 6ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:11:02+00:00 NOTICE Square.js Response:
 Array
(
    [brand] => VISA
    [expMonth] => XX
    [expYear] => XXXX
    [last4] => 0002
)
 CONTEXT: {"_legacy":true}
2025-07-23T02:11:02+00:00 NOTICE [Performance] validate_payment_data completed in 0ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:11:02+00:00 NOTICE [Performance] generate_payment_nonce completed in 946ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:11:02+00:00 NOTICE Request
method:
uri: createCard
user-agent: WooCommerce-Square/4.9.4 (WooCommerce/10.0.2; WordPress/6.8.2)
headers: Array
(
)
body:
duration: 0.4132s
 CONTEXT: {"_legacy":true}
2025-07-23T02:11:02+00:00 NOTICE Response
code: 400
message:
headers: Array
(
    [0] => HTTP/2 400
    [date] => Wed, 23 Jul 2025 02:11:02 GMT
    [content-type] => application/json
    [content-length] => 134
    [cf-ray] => 9637a513aa5068f4-IAD
    [cf-cache-status] => DYNAMIC
    [content-encoding] => gzip
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [vary] => Origin, Accept-Encoding
    [square-version] => 2025-01-23
    [x-content-type-options] => nosniff
    [x-download-options] => noopen
    [x-envoy-decorator-operation] => /v2/cards/**
    [x-frame-options] => SAMEORIGIN
    [x-permitted-cross-domain-policies] => none
    [x-speleo-traceid] => CDN-1f9bf689-d73e-400f-a257-c56e4f9dbefa
    [x-sq-dc] => aws
    [x-sq-istio-migration-ingress-proxy] => sq-envoy
    [x-sq-istio-migration-ingress-region] => us-east-1
    [x-sq-region] => us-east-1
    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm=BSqCJpIe7y3etF33GMamEUvmRWbpf0pcuCZYo74p8P8-1753236662-1.0.1.1-H3n6qnwtJ9ftcEhfj74Ajy100.uUAL0cRfmaVO967v8.jwyQzeKYJ.R0mlI8Az.LSWuRCit0WlcGoynMYDKYCC.rxtjvj4UCJQPOHyxsBjw; path=/; expires=Wed, 23-Jul-25 02:41:02 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [server] => cloudflare
)
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => INVALID_CARD_DATA
            [detail:Square\Models\Error:private] => Invalid card data.
            [field:Square\Models\Error:private] => source_id
        )

)
 CONTEXT: {"_legacy":true}
2025-07-23T02:12:02+00:00 NOTICE [Performance] validate_payment_data completed in 6ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:12:03+00:00 NOTICE [Performance] validate_payment_data completed in 0ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:12:03+00:00 NOTICE Square.js Response:
 Array
(
    [brand] => VISA
    [expMonth] => XX
    [expYear] => XXXX
    [last4] => 0002
)
 CONTEXT: {"_legacy":true}
2025-07-23T02:12:03+00:00 NOTICE [Performance] generate_payment_nonce completed in 2.303s with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:12:04+00:00 NOTICE Request
method:
uri: createCard
user-agent: WooCommerce-Square/4.9.4 (WooCommerce/10.0.2; WordPress/6.8.2)
headers: Array
(
)
body:
duration: 0.50029s
 CONTEXT: {"_legacy":true}
2025-07-23T02:12:04+00:00 NOTICE Response
code: 400
message:
headers: Array
(
    [0] => HTTP/2 400
    [date] => Wed, 23 Jul 2025 02:12:04 GMT
    [content-type] => application/json
    [content-length] => 134
    [cf-ray] => 9637a695ebbc078c-IAD
    [cf-cache-status] => DYNAMIC
    [content-encoding] => gzip
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [vary] => Origin, Accept-Encoding
    [square-version] => 2025-01-23
    [x-content-type-options] => nosniff
    [x-download-options] => noopen
    [x-envoy-decorator-operation] => /v2/cards/**
    [x-frame-options] => SAMEORIGIN
    [x-permitted-cross-domain-policies] => none
    [x-speleo-traceid] => CDN-cf132422-ca3e-4e89-8e8c-53a67eaff9cd
    [x-sq-dc] => aws
    [x-sq-istio-migration-ingress-proxy] => sq-envoy
    [x-sq-istio-migration-ingress-region] => us-east-1
    [x-sq-region] => us-east-1
    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm=fe9hOfNGzAl96DTei6TcqJyLIpKobGmNmgY8euguCpU-1753236724-1.0.1.1-yzQqo5_IcVAmw3sue_yqlMFsjwuPT_H5IcOqPXz5Ztv3xF8g.98IQ.S1r_wJefp_qzHUdZxMPk8219FvleEulO6.bHs310.uvGs7S5AMM6s; path=/; expires=Wed, 23-Jul-25 02:42:04 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [server] => cloudflare
)
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => INVALID_CARD_DATA
            [detail:Square\Models\Error:private] => Invalid card data.
            [field:Square\Models\Error:private] => source_id
        )

)
 CONTEXT: {"_legacy":true}
2025-07-23T02:13:42+00:00 NOTICE [Performance] validate_payment_data completed in 7ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:13:44+00:00 NOTICE Square.js Response:
 Array
(
    [brand] => VISA
    [expMonth] => XX
    [expYear] => XXXX
    [last4] => 4421
)
 CONTEXT: {"_legacy":true}
2025-07-23T02:13:44+00:00 NOTICE [Performance] generate_payment_nonce completed in 2.850s with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:13:44+00:00 NOTICE [Performance] validate_payment_data completed in 0ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-07-23T02:13:45+00:00 NOTICE Request
method:
uri: createCard
user-agent: WooCommerce-Square/4.9.4 (WooCommerce/10.0.2; WordPress/6.8.2)
headers: Array
(
)
body:
duration: 0.43421s
 CONTEXT: {"_legacy":true}
2025-07-23T02:13:45+00:00 NOTICE Response
code: 400
message:
headers: Array
(
    [0] => HTTP/2 400
    [date] => Wed, 23 Jul 2025 02:13:45 GMT
    [content-type] => application/json
    [content-length] => 134
    [cf-ray] => 9637a90ed9aae5b4-IAD
    [cf-cache-status] => DYNAMIC
    [content-encoding] => gzip
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [vary] => Origin, Accept-Encoding
    [square-version] => 2025-01-23
    [x-content-type-options] => nosniff
    [x-download-options] => noopen
    [x-envoy-decorator-operation] => /v2/cards/**
    [x-frame-options] => SAMEORIGIN
    [x-permitted-cross-domain-policies] => none
    [x-speleo-traceid] => CDN-4f03bad8-d454-4282-a84d-eaddba9f3545
    [x-sq-dc] => aws
    [x-sq-istio-migration-ingress-proxy] => sq-envoy
    [x-sq-istio-migration-ingress-region] => us-east-1
    [x-sq-region] => us-east-1
    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm=W9Vfmcj8Nj.SEttxq3ZrqW9Fg2lTt7JH5pCnqeZFJLk-1753236825-1.0.1.1-L9oNW2NUtBqsPjwdXdNcxTH8BZZZ5LAEtimJ7ILa_QKA6nb0jIxHWBOjz1qp08KBpcaSRVjY4K8eXszX12f_QyRc_WPjpLxEdYXJz._mC4Q; path=/; expires=Wed, 23-Jul-25 02:43:45 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [server] => cloudflare
)
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => INVALID_CARD_DATA
            [detail:Square\Models\Error:private] => Invalid card data.
            [field:Square\Models\Error:private] => source_id
        )

)
 CONTEXT: {"_legacy":true}
```

**Comment by bigscaryduck** [comment]
This is causing enough problems where my company has decided to turn off all paid channels until it is resolved, we have tried rolling back to older versions of the plugin and the issue persists. 

Any help on this ASAP would be very appreciated! Thanks.

**Comment by dgogia-creator** [comment]
Answers inline:
Existing customer with expired ccof trying to update a new card gets "Invalid card Data" error with the same "square-credit-card" log file as shown above.
Answer> CCOF doesn't expire for existing customer, existing customer trying to use a new card from checkout page and even if the customer tries to update a payment method from the website dashboard experiences the same issue. Customer message is "use another form of payment"

As far as I know, ccof does not expire on its own unless it was deleted from the customer profile. Can you explain in what scenario the ccof would expire?


Answer> CCOF for existing customers do not expire nor is deleted from user profile. 

New customer trying to place order. Customer ID is created in square but not updated on wp/wc_user. Same error message "Invalid Card Data".


If you visit the Customer's profile admin page, you'll see a text field called Customer ID. Can you please verify if the Customer ID exists for the new customer?

Answer> No,the customer ID does not gets updated on customers profile. 

My interim Solution: Looking at the square-credit-card log file on woocommerce >status >logs and copying most recent Customer ID from log and saving it in the user profile manually. Then processing payment from Square dashboard with customer on phone call to save CCOF. Doing this, it saves the CCOF and the last 4 digits are shown on the customer profile page.

**Comment by Sidsector9** [comment]
Thank you all for the response. Just wanted to update you that we are working on this on priority. 

@bigscaryduck , I am assuming that you masked the sensitive details of the customers (confirming that the customer isn't actually filling these):

```
"updated_at": "2025-07-23T02:10:03Z",
        "given_name": "Dummy",
        "family_name": "Dummy",
        "email_address": "Dummy@gmail.com",
        "address": {
            "address_line_1": "Dummy",
            "locality": "Dummy",
            "administrative_district_level_1": "CA",
            "postal_code": "95222",
            "country": "US"
        },
```

**Comment by bigscaryduck** [comment]
Thanks for keeping us posted @Sidsector9 ,

I did mask identifying information, I kept the card type and last4 but hid the Exp Month and Exp Year so that you could see it was more then 1 card attempted. Additionally, I hid contact information with the term "Dummy".

**Comment by dgogia-creator** [comment]
Yes, I did mask it to dummy as well

**Comment by bigscaryduck** [comment]
I don't think it was answered, will this Pull Request resolve this issue? It seems to rework this flow that is having an issue. 
https://github.com/woocommerce/woocommerce-square/pull/379

**Comment by iamdharmesh** [comment]
> I don't think it was answered, will this Pull Request resolve this issue? It seems to rework this flow that is having an issue.
https://github.com/woocommerce/woocommerce-square/pull/379

@bigscaryduck PR #379 addresses a different issue. However, it also includes an upgrade to the new payment flow. I haven't been able to reproduce this issue yet, so I can't confirm whether the PR will fix it or not. Thanks!

**Comment by bigscaryduck** [comment]
Thanks, if there is anything else I can provide to help you debug or reproduce please let me know.

**Comment by dgogia-creator** [comment]
Is there anything we can help to recreate, its pretty straightforward and easy to reproduce.i xa do a remote desktop session and show you. The production environment is a.mess now because of this as no new user can save their cards on file. It can't be simpler than that. New user cant save ccof  and existing users cant update their cards. Or use a new card for payment. Its become a joke now and we're losing revenue big time because of  this mess.

**Comment by dgogia-creator** [comment]
Is there anyway to escalate the severity of this bug to Severity 1?we need a patch or a plugin update asap. Like yesterday

**Comment by bigscaryduck** [comment]
Sorry to push but is there any update on this? It is really causing major issues for our customers, we are looking at finding a different payment processor because we need a solution. 

I have tried rolling back up the past 3 releases and the issue persists. Any ideas on how to get this working would be appreciated. I am also more then happy to jump on a screenshare, send more detailed logs, or whatever else that could help expedited this fix.

**Comment by Sidsector9** [comment]
Hi all, just updating everyone.

We tried with a bunch of credit cards and we were able to reproduce the issue with some cards on `trunk` (0cbf9cf), which is version 4.9.6. However, I also tested with version 4.8.0 and it fails with older versions too.

We tested with the fixes in PR #379 and it seems to fix the issue. Please note that the PR is under testing, and a release will be scheduled next week.

**Comment by duffk** [comment]
Chiming in to say that we are having the same issues. We can not add a credit card to customer profile or update payment method for a renewing subscription. We need a fix for this asap as well!

**Comment by iamdharmesh** [comment]
@nathanaelphilip @dgogia-creator @bigscaryduck @duffk Just wanted to check if the 4.9.7 release has resolved this issue for you. Thanks!

**Comment by dgogia-creator** [comment]
Yes. its working today.Thank You!

**Comment by nicdwilson** [comment]
Can we confirm that we are not submitting verification tokens for previously stored cards? This appears to be triggering an error in some cases where we may be submitting non-null data where residual data is [picked up here](https://github.com/woocommerce/woocommerce-square/blob/3dd0bcfbabe7f8c229750da4778e9313e2702db4/includes/Gateway.php#L348).

We are submitting

```
"verification_token":"saved_card",
```

When submitted, we seem to get the following error on stored payments.

```
 [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => BAD_REQUEST
            [detail:Square\Models\Error:private] => Invalid verification_token: saved_card
            [field:Square\Models\Error:private] => verification_token
        )
```

**Comment by iamdharmesh** [comment]
Hi @nicdwilson 👋,

> Can we confirm that we are not submitting verification tokens for previously stored cards? This appears to be triggering an error in some cases where we may be submitting non-null data where residual data is [picked up here](https://github.com/woocommerce/woocommerce-square/blob/3dd0bcfbabe7f8c229750da4778e9313e2702db4/includes/Gateway.php#L348).

Yes, with new payment flow we don't have to send verification token for the saved card or new cards. Regarding this `saved_card` data, we already fixed it in PR #379 and it is released in Square 4.9.7. Could you please ask merchant to upgrade to the latest version of Square? Please let me know if issue still persists for them.

Thanks!

**Comment by iamdharmesh** [comment]
Hi, @nathanaelphilip @bigscaryduck @duffk Sorry for ping again but just want to confirm if this is already fixed for you now. Thanks!

**Comment by lynnjat7** [comment]
Hi @iamdharmesh The merchant affected by this says that they are still seeing the issue that Nic described above, and that it is NOT resolved by upgrading to 4.9.7.

*After* upgrading, they are seeing the issue Nic reported above. Here is a longer excerpt from their log file (with any/all customer information and access codes removed for privacy):

```
body: {"source_id":"ccof:xxx","idempotency_key":"cccc","amount_money":{"amount":29411,"currency":"USD"},"autocomplete":true,"order_id":"xxx","customer_id":"xxx","location_id":"L2PQ91AXKR200","reference_id":"719409","verification_token":"saved_card","buyer_email_address":"customer1@gmail.com","billing_address":{"address_line_1":"address","address_line_2":"","locality":"City","administrative_district_level_1":"CA","postal_code":"93720","country":"US","first_name":"Name","last_name":"Last"},"shipping_address":{"address_line_1":"Address","address_line_2":"","locality":"City","administrative_district_level_1":"CA","postal_code":"93720","country":"US","first_name":"Name","last_name":"Last"},"note":"Central Milling - Order 719409","customer_details":{"customer_initiated":true}}
duration: 0.29943s
 CONTEXT: {"_legacy":true}
2025-08-05T00:00:31+00:00 NOTICE Response
code: 400
message:
headers: Array
(
    [0] => HTTP/2 400
    [date] => Tue, 05 Aug 2025 00:00:31 GMT
    [content-type] => application/json
    [content-length] => 155
    [cf-ray] => 96a203c0c89c31df-PDX
    [cf-cache-status] => DYNAMIC
    [strict-transport-security] => max-age=631152000; includeSubDomains; preload
    [frame-options] => DENY
    [square-version] => 2025-01-23
    [squareup--connect--v2--common--versionmetadata-bin] => CgoyMDI1LTAxLTIz
    [x-content-type-options] => nosniff
    [x-envoy-decorator-operation] => /v2/payments/**
    [x-frame-options] => DENY
    [x-sq-dc] => Array
        (
            [0] => aws
            [1] => aws
        )

    [x-sq-istio-migration-egress-proxy] => sq-envoy
    [x-sq-istio-migration-egress-region] => us-west-2
    [x-sq-istio-migration-ingress-proxy] => sq-envoy
    [x-sq-istio-migration-ingress-region] => Array
        (
            [0] => us-west-2
            [1] => us-west-2
        )

    [x-sq-region] => Array
        (
            [0] => us-west-2
            [1] => us-west-2
        )

    [x-xss-protection] => 1; mode=block
    [set-cookie] => __cf_bm=cookie_code; path=/; expires=Tue, 05-Aug-25 00:30:31 GMT; domain=.connect.squareup.com; HttpOnly; Secure; SameSite=None
    [vary] => Accept-Encoding
    [server] => cloudflare
)
body: Array
(
    [0] => Square\Models\Error Object
        (
            [category:Square\Models\Error:private] => INVALID_REQUEST_ERROR
            [code:Square\Models\Error:private] => BAD_REQUEST
            [detail:Square\Models\Error:private] => Invalid verification_token: saved_card
            [field:Square\Models\Error:private] => verification_token
        )

)
 CONTEXT: {"_legacy":true}
2025-08-05T00:00:31+00:00 NOTICE Status code BAD_REQUEST: Invalid verification_token: saved_card CONTEXT: {"_legacy":true}
2025-08-05T00:01:31+00:00 NOTICE [Performance] initialize_payment_form completed in 1.603s with 1.14MB of memory usage CONTEXT: {"_legacy":true}
2025-08-05T00:02:20+00:00 NOTICE [Performance] validate_payment_data completed in 1ms with 0.00KB of memory usage CONTEXT: {"_legacy":true}
2025-08-05T00:02:26+00:00 NOTICE Request
method:
uri: createOrder
user-agent: WooCommerce-Square/4.9.7 (WooCommerce/10.0.4; WordPress/6.8.2)
headers: Array
(
)
```

You can see clearly that the user-agent here is 4.9.7 for Square.

Any thoughts?

**Comment by lynnjat7** [comment]
Oh, forgot to add that this error happens when a new customer buys a new subscription, and it tries to save the payment information for the card for the subscription.

**Comment by nicdwilson** [comment]
This merchant is using 4.9.7.  Confirmed by the log  file headers:

```
 CONTEXT: {"_legacy":true}
2025-08-05T00:00:31+00:00 NOTICE Request
method:
uri: createPayment
user-agent: WooCommerce-Square/4.9.7 (WooCommerce/10.0.4; WordPress/6.8.2)
headers: Array
```

**Comment by solstudioim** [comment]
Hello @iamdharmesh could you please have a look a this?

**Comment by Sidsector9** [comment]
@nicdwilson @lynnjat7 technically the `saved_card` parameter should not exist in the request as it was removed in 4.9.7.
As it is still visible, it suggests that a stale copy of JS assets is sending the parameter.
The logs suggest that the merchant site is running behind Cloudflare. Is it possible to request the merchant to disable Cloudflare or clear the Cloudflare cache and try it in incognito, just so that we can rule out the possibility of cached content?

**Comment by wpniall** [comment]
Thank you, @Sidsector9 . I've asked the merchant in #10068259-zen. We'll let you know what they say.

**Comment by duffk** [comment]
@iamdharmesh This is still a problem for us. We have updated to 4.9.8 for woo square and woo 10.1.2 and today i have the following error still - An error occurred, please try again or try an alternate form of payment.
This happens when I try to add a credit card to the payment methods to update the customer record for a subscription. I was able to charge the card through a different system, so I know that the card information is correct.

**Comment by mouligreenlaw** [comment]
@Sidsector9 We followed up with the user on 0068259-zen and they have confirmed that since updating to 4.9.8 they are only getting a few failures and those have normal error messages so they are content with the current situation.

**Comment by shameemreza** [comment]
Another report here: 10237612-zen

**Comment by jeffpaul** [comment]
@mouligreenlaw @shameemreza there's been so much back-and-forth on this issue and its hard to tell what issues remain / what merchants are still seeing with us attempting to address in shipped software (4.9.7, 4.9.8) specifically targeting this issue.  If you're seeing actual issues of concerns with merchants please either share that explicitly here or open a new issue to track separately… thanks!
